enum Constants {
  FETCH_DASHBOARD_DATA = 'FETCH_DASHBOARD_DATA',
  FETCH_DASHBOARD_ON_ERROR = 'FETCH_DASHBOARD_ON_ERROR',
  FETCH_DASHBOARD_LOADING = 'FETCH_DASHBOARD_LOADING',
  RESOLVE_DASHBOARD_ERROR = 'RESOLVE_DASHBOARD_ERROR',
  RESET_DASHBOARD = 'RESET_DASHBOARD',
}

export default Constants
