enum Constants {
  FETCH_DETAILS_DATA = 'FETCH_DETAILS_DATA',
  FETCH_DETAILS_LOADING = 'FETCH_DETAILS_LOADING',
  FETCH_DETAILS_ON_ERROR = 'FETCH_DETAILS_ON_ERROR',
  RESOLVE_DETAILS_ERROR = 'RESOLVE_DETAILS_ERROR',
  RESET_DETAILS = 'RESET_DETAILS',
}

export default Constants
